"use client";

import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";


export default function TermsPage() {
    const router = useRouter();
    const t = useTranslations();

    return (
        <div className="flex flex-col min-h-screen bg-gray-50">
            {/* Top Bar */}
            <div className="sticky top-0 z-20 flex items-center bg-white shadow-sm h-14 px-4">
                <button
                    onClick={() => router.back()}
                    className="mr-4 p-2 rounded-full hover:bg-gray-200 transition"
                >
                    <span className="text-xl">←</span>
                </button>
                <h1 className="text-lg font-semibold">{t("termsPage.title")}</h1>
            </div>

            {/* Content */}
            <div className="flex-1 p-6 max-w-3xl mx-auto w-full space-y-6 text-gray-800 text-sm leading-relaxed">
                <p className="text-gray-500 text-xs italic">
                    Last updated: 20 May 2025
                </p>

                <h2 className="text-xl font-bold">1. Acceptance of Terms</h2>
                <p>
                    By using Minimind (“we”, “our”, or “the Service”), you confirm that you are legally eligible to enter into this agreement and agree to abide by all terms stated herein. If you disagree, you must not use this service.
                </p>

                <h2 className="text-xl font-bold">2. Authority & Ownership</h2>
                <p>
                    Minimind reserves full ownership and control over all platform features, tokens, AI models, and content generation logic. We retain the absolute right to restrict, revoke, or deny access to any user at any time, without explanation or liability.
                </p>

                <h2 className="text-xl font-bold">3. AI Content Disclaimer</h2>
                <p>
                    The content generated by Minimind's AI is for entertainment, convenience, and general guidance only. We do not guarantee accuracy, legality, ethical alignment, or appropriateness of any generated content. You agree that:
                </p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>All AI content is used at your own risk.</li>
                    <li>Minimind is not liable for any outcome derived from AI-generated responses.</li>
                    <li>AI output must not be treated as medical, legal, financial, or professional advice.</li>
                </ul>

                <h2 className="text-xl font-bold">4. Token Usage & Billing</h2>
                <p>
                    Tokens are a prepaid digital utility within Minimind and are deducted when using premium features. All token purchases are final and non-refundable unless required by applicable law. You are solely responsible for monitoring and managing your token usage.
                </p>

                <h2 className="text-xl font-bold">5. User Conduct</h2>
                <p>
                    You agree not to use the platform for any illegal, harmful, abusive, exploitative, or malicious purposes. We may log, monitor, and audit usage activity to enforce compliance. Violation may result in account suspension or permanent ban without refund or appeal.
                </p>

                <h2 className="text-xl font-bold">6. Data & Privacy</h2>
                <p>
                    Minimind collects only essential information (e.g., login ID, preferences, token usage) for platform functionality. We do not sell personal data to third parties. By using the Service, you consent to our data collection and retention policies as outlined here.
                </p>

                <h2 className="text-xl font-bold">7. Service Availability</h2>
                <p>
                    We make no guarantees that Minimind will operate without interruption or error. Features may be modified, removed, or discontinued at any time without notice. We are not liable for downtime, service disruption, or data loss.
                </p>

                <h2 className="text-xl font-bold">8. Limitation of Liability</h2>
                <p>
                    To the maximum extent permitted by law:
                </p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Minimind is not liable for indirect, incidental, or consequential damages.</li>
                    <li>Total liability is limited to the lesser of (a) the amount you paid in the last 12 months, or (b) USD $10.</li>
                    <li>You waive the right to participate in any class action or collective proceeding against us.</li>
                </ul>

                <h2 className="text-xl font-bold">9. Termination & Enforcement</h2>
                <p>
                    We reserve full authority to terminate any account or session without notice or reason. All decisions are final. We may enforce this policy at our sole discretion.
                </p>

                <h2 className="text-xl font-bold">10. Jurisdiction</h2>
                <p>
                    These Terms are governed by the laws of Hong Kong. You agree that all legal disputes shall be resolved exclusively in the courts of this jurisdiction. You waive all objections to venue and consent to personal jurisdiction.
                </p>

                <h2 className="text-xl font-bold">11. Updates</h2>
                <p>
                    Minimind may modify these Terms at any time. Continued use of the Service constitutes acceptance of the revised Terms. It is your responsibility to review this page periodically.
                </p>

                <h2 className="text-xl font-bold">12. Contact</h2>
                <p>
                    For legal inquiries, contact us at: <a href="mailto:inquiry@minimind.pro" className="text-blue-600 hover:underline">inquiry@minimind.pro</a>
                </p>
            </div>
        </div>
    );
}
